# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: tour
    weight: 10
  - name: Maps
    url: maps
    weight: 20
  - name: Data
    url: data
    weight: 30
  - name: Risk toolkit
    url: software
    weight: 40
  - name: People
    url: people
    weight: 70
  - name: Training
    url: event
    weight: 50
  - name: News
    url: news
    weight: 60
  - name: Contact
    url: contact
    weight: 80
